(*Generated by Lem from pervasives_extra.lem.*)
open HolKernel Parse boolLib bossLib;
open lem_pervasives_sailTheory lem_function_extraTheory lem_maybe_extraTheory lem_map_extraTheory lem_num_extraTheory lem_set_extra_sailTheory lem_set_helpersTheory lem_list_extra_sailTheory lem_string_extra_sailTheory lem_assert_extraTheory lem_show_extraTheory lem_machine_wordTheory;

val _ = numLib.prefer_num();



val _ = new_theory "lem_pervasives_extra_sail"

 

(*include import Pervasives*) 
(*include import Function_extra Maybe_extra Map_extra Num_extra Set_extra Set_helpers List_extra String_extra Assert_extra Show_extra Machine_word*)
val _ = export_theory()

